name: Build Windows App

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows Desktop Support
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Create .env File
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env

      - name: Build Windows App
        run: flutter build windows --release

      - name: Copy Required DLLs
        run: |
          cp windows/sqlite3.dll build/windows/x64/runner/Release/
          cp windows/sqlite3.def build/windows/x64/runner/Release/
          cp windows/msvcp140.dll build/windows/x64/runner/Release/
          cp windows/vcruntime140.dll build/windows/x64/runner/Release/
          cp windows/vcruntime140_1.dll build/windows/x64/runner/Release/

      - name: Debug Build Output
        run: ls -Recurse build/windows/x64/runner/Release/

      - name: Package Windows App
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath windows-app.zip

      - name: Upload Windows App
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: windows-app.zip
