name: Build Windows App

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows Desktop Support
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Package Windows App
        run: Compress-Archive -Path build\windows\runner\Release\* -DestinationPath windows-app.zip

      - name: Upload Windows App
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: windows-app.zip
